### ISSUE TITLE
qhist log file write location can be bad

### ISSUE THREAD

**Issue by vanderwb** [negin513/ncar-dask-monitor#10]
As reported by @sjsprecious It appears that this tool wishes to write a temporary dump of qhist output to $PWD/log.txt. But this causes an error if you are currently within a path that you don't have write permissions to. The tool should use a better default path, like `${TMPDIR:-/glade/derecho/scratch/$USER}/qhist-log.txt`.

**Comment by vanderwb** [comment]
@negin513 - no big rush on this, but just wanted you to be aware of this failure mode.

**Comment by negin513** [comment]
Thanks @vanderwb and @sjsprecious for reporting this issue. This issue should be fixed with the recent changes.

**Comment by negin513** [comment]
Thanks again for reporting this issue. This should be fixed now and I am closing this issue.
